services:
  pg:
    image: postgres:17.4-alpine3.21
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${PG_NAME}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASS}
    volumes:
      - billing-service-pg-data:/var/lib/postgresql/data
    ports:
      - ${PG_PORT}:5432

volumes:
  billing-service-pg-data:
    name: mu-billing-service-pg