// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"context"
	"fmt"
	"github.com/jmoiron/sqlx"
	"github.com/tehrelt/mu-lib/tracer"
	"github.com/tehrelt/mu/user-service/internal/config"
	"github.com/tehrelt/mu/user-service/internal/storage/pg/userstorage"
	"github.com/tehrelt/mu/user-service/internal/transport/grpc"
	"go.opentelemetry.io/otel/trace"
	"log/slog"
	"time"
)

import (
	_ "github.com/jackc/pgx/stdlib"
)

// Injectors from wire.go:

func New(ctx context.Context) (*App, func(), error) {
	configConfig := config.New()
	db, cleanup, err := _pg(configConfig)
	if err != nil {
		return nil, nil, err
	}
	userStorage := userstorage.New(db)
	server := _grpc(configConfig, userStorage, userStorage)
	v := _servers(server)
	tracer, err := _tracer(ctx, configConfig)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	app := newApp(v, tracer)
	return app, func() {
		cleanup()
	}, nil
}

// wire.go:

func _pg(cfg *config.Config) (*sqlx.DB, func(), error) {
	host := cfg.Postgres.Host
	port := cfg.Postgres.Port
	user := cfg.Postgres.User
	pass := cfg.Postgres.Pass
	name := cfg.Postgres.Name

	cs := fmt.Sprintf(`postgres://%s:%s@%s:%d/%s?sslmode=disable`, user, pass, host, port, name)

	db, err := sqlx.Connect("pgx", cs)
	if err != nil {
		return nil, nil, err
	}
	slog.Debug("connecting to database", slog.String("conn", cs))
	t := time.Now()
	if err := db.Ping(); err != nil {
		slog.Error("failed to connect to database", slog.String("err", err.Error()), slog.String("conn", cs))
		return nil, func() { db.Close() }, err
	}
	slog.Info("connected to database", slog.String("ping", fmt.Sprintf("%2.fs", time.Since(t).Seconds())))

	return db, func() { db.Close() }, nil
}

func _grpc(cfg *config.Config, creator grpc.UserCreator, provider grpc.UserProvider) *grpc.Server {
	return grpc.New(cfg, creator, provider)
}

func _servers(g *grpc.Server) []Server {
	return []Server{g}
}

func _tracer(ctx context.Context, cfg *config.Config) (trace.Tracer, error) {
	jaeger := cfg.Jaeger.Endpoint
	appname := cfg.App.Name
	slog.Debug("connecting to jaeger", slog.String("jaeger", jaeger), slog.String("appname", appname))

	return tracer.SetupTracer(ctx, jaeger, appname)
}
