// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.4
// source: proto/house.proto

package housepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type House struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Address           string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	RoomsQty          int64                  `protobuf:"varint,3,opt,name=rooms_qty,json=roomsQty,proto3" json:"rooms_qty,omitempty"`
	ResidentsQty      int64                  `protobuf:"varint,4,opt,name=residents_qty,json=residentsQty,proto3" json:"residents_qty,omitempty"`
	CreatedAt         int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt         int64                  `protobuf:"varint,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	ConnectedServices []string               `protobuf:"bytes,7,rep,name=connected_services,json=connectedServices,proto3" json:"connected_services,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *House) Reset() {
	*x = House{}
	mi := &file_proto_house_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *House) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*House) ProtoMessage() {}

func (x *House) ProtoReflect() protoreflect.Message {
	mi := &file_proto_house_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use House.ProtoReflect.Descriptor instead.
func (*House) Descriptor() ([]byte, []int) {
	return file_proto_house_proto_rawDescGZIP(), []int{0}
}

func (x *House) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *House) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *House) GetRoomsQty() int64 {
	if x != nil {
		return x.RoomsQty
	}
	return 0
}

func (x *House) GetResidentsQty() int64 {
	if x != nil {
		return x.ResidentsQty
	}
	return 0
}

func (x *House) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *House) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *House) GetConnectedServices() []string {
	if x != nil {
		return x.ConnectedServices
	}
	return nil
}

type CreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	RoomsQty      int64                  `protobuf:"varint,2,opt,name=rooms_qty,json=roomsQty,proto3" json:"rooms_qty,omitempty"`
	ResidentsQty  int64                  `protobuf:"varint,3,opt,name=residents_qty,json=residentsQty,proto3" json:"residents_qty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_proto_house_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_house_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_proto_house_proto_rawDescGZIP(), []int{1}
}

func (x *CreateRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *CreateRequest) GetRoomsQty() int64 {
	if x != nil {
		return x.RoomsQty
	}
	return 0
}

func (x *CreateRequest) GetResidentsQty() int64 {
	if x != nil {
		return x.ResidentsQty
	}
	return 0
}

type CreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResponse) Reset() {
	*x = CreateResponse{}
	mi := &file_proto_house_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResponse) ProtoMessage() {}

func (x *CreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_house_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResponse.ProtoReflect.Descriptor instead.
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return file_proto_house_proto_rawDescGZIP(), []int{2}
}

func (x *CreateResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type HouseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HouseId       string                 `protobuf:"bytes,1,opt,name=house_id,json=houseId,proto3" json:"house_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HouseRequest) Reset() {
	*x = HouseRequest{}
	mi := &file_proto_house_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HouseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HouseRequest) ProtoMessage() {}

func (x *HouseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_house_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HouseRequest.ProtoReflect.Descriptor instead.
func (*HouseRequest) Descriptor() ([]byte, []int) {
	return file_proto_house_proto_rawDescGZIP(), []int{3}
}

func (x *HouseRequest) GetHouseId() string {
	if x != nil {
		return x.HouseId
	}
	return ""
}

type HouseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	House         *House                 `protobuf:"bytes,1,opt,name=house,proto3" json:"house,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HouseResponse) Reset() {
	*x = HouseResponse{}
	mi := &file_proto_house_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HouseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HouseResponse) ProtoMessage() {}

func (x *HouseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_house_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HouseResponse.ProtoReflect.Descriptor instead.
func (*HouseResponse) Descriptor() ([]byte, []int) {
	return file_proto_house_proto_rawDescGZIP(), []int{4}
}

func (x *HouseResponse) GetHouse() *House {
	if x != nil {
		return x.House
	}
	return nil
}

type ListHousesByIdsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHousesByIdsRequest) Reset() {
	*x = ListHousesByIdsRequest{}
	mi := &file_proto_house_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHousesByIdsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHousesByIdsRequest) ProtoMessage() {}

func (x *ListHousesByIdsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_house_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHousesByIdsRequest.ProtoReflect.Descriptor instead.
func (*ListHousesByIdsRequest) Descriptor() ([]byte, []int) {
	return file_proto_house_proto_rawDescGZIP(), []int{5}
}

func (x *ListHousesByIdsRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListHousesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	House         *House                 `protobuf:"bytes,1,opt,name=house,proto3" json:"house,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHousesResponse) Reset() {
	*x = ListHousesResponse{}
	mi := &file_proto_house_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHousesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHousesResponse) ProtoMessage() {}

func (x *ListHousesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_house_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHousesResponse.ProtoReflect.Descriptor instead.
func (*ListHousesResponse) Descriptor() ([]byte, []int) {
	return file_proto_house_proto_rawDescGZIP(), []int{6}
}

func (x *ListHousesResponse) GetHouse() *House {
	if x != nil {
		return x.House
	}
	return nil
}

type ListConnectedServicesOfHouseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HouseId       string                 `protobuf:"bytes,1,opt,name=house_id,json=houseId,proto3" json:"house_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConnectedServicesOfHouseRequest) Reset() {
	*x = ListConnectedServicesOfHouseRequest{}
	mi := &file_proto_house_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConnectedServicesOfHouseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConnectedServicesOfHouseRequest) ProtoMessage() {}

func (x *ListConnectedServicesOfHouseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_house_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConnectedServicesOfHouseRequest.ProtoReflect.Descriptor instead.
func (*ListConnectedServicesOfHouseRequest) Descriptor() ([]byte, []int) {
	return file_proto_house_proto_rawDescGZIP(), []int{7}
}

func (x *ListConnectedServicesOfHouseRequest) GetHouseId() string {
	if x != nil {
		return x.HouseId
	}
	return ""
}

type ListConnectedServicesOfHouseResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ConnectedServices []string               `protobuf:"bytes,1,rep,name=connected_services,json=connectedServices,proto3" json:"connected_services,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ListConnectedServicesOfHouseResponse) Reset() {
	*x = ListConnectedServicesOfHouseResponse{}
	mi := &file_proto_house_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConnectedServicesOfHouseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConnectedServicesOfHouseResponse) ProtoMessage() {}

func (x *ListConnectedServicesOfHouseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_house_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConnectedServicesOfHouseResponse.ProtoReflect.Descriptor instead.
func (*ListConnectedServicesOfHouseResponse) Descriptor() ([]byte, []int) {
	return file_proto_house_proto_rawDescGZIP(), []int{8}
}

func (x *ListConnectedServicesOfHouseResponse) GetConnectedServices() []string {
	if x != nil {
		return x.ConnectedServices
	}
	return nil
}

var File_proto_house_proto protoreflect.FileDescriptor

var file_proto_house_proto_rawDesc = string([]byte{
	0x0a, 0x11, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x22, 0xe0, 0x01, 0x0a, 0x05, 0x48,
	0x6f, 0x75, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1b,
	0x0a, 0x09, 0x72, 0x6f, 0x6f, 0x6d, 0x73, 0x5f, 0x71, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x08, 0x72, 0x6f, 0x6f, 0x6d, 0x73, 0x51, 0x74, 0x79, 0x12, 0x23, 0x0a, 0x0d, 0x72,
	0x65, 0x73, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x73, 0x5f, 0x71, 0x74, 0x79, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0c, 0x72, 0x65, 0x73, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x73, 0x51, 0x74, 0x79,
	0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12,
	0x1d, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x2d,
	0x0a, 0x12, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x65, 0x64, 0x5f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x09, 0x52, 0x11, 0x63, 0x6f, 0x6e, 0x6e,
	0x65, 0x63, 0x74, 0x65, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x22, 0x6b, 0x0a,
	0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18,
	0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x72, 0x6f, 0x6f, 0x6d,
	0x73, 0x5f, 0x71, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x72, 0x6f, 0x6f,
	0x6d, 0x73, 0x51, 0x74, 0x79, 0x12, 0x23, 0x0a, 0x0d, 0x72, 0x65, 0x73, 0x69, 0x64, 0x65, 0x6e,
	0x74, 0x73, 0x5f, 0x71, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x72, 0x65,
	0x73, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x73, 0x51, 0x74, 0x79, 0x22, 0x20, 0x0a, 0x0e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x29, 0x0a, 0x0c,
	0x48, 0x6f, 0x75, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08,
	0x68, 0x6f, 0x75, 0x73, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x68, 0x6f, 0x75, 0x73, 0x65, 0x49, 0x64, 0x22, 0x33, 0x0a, 0x0d, 0x48, 0x6f, 0x75, 0x73, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x05, 0x68, 0x6f, 0x75, 0x73,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x2e,
	0x48, 0x6f, 0x75, 0x73, 0x65, 0x52, 0x05, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x22, 0x28, 0x0a, 0x16,
	0x4c, 0x69, 0x73, 0x74, 0x48, 0x6f, 0x75, 0x73, 0x65, 0x73, 0x42, 0x79, 0x49, 0x64, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x38, 0x0a, 0x12, 0x4c, 0x69, 0x73, 0x74, 0x48, 0x6f,
	0x75, 0x73, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x05,
	0x68, 0x6f, 0x75, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x68, 0x6f,
	0x75, 0x73, 0x65, 0x2e, 0x48, 0x6f, 0x75, 0x73, 0x65, 0x52, 0x05, 0x68, 0x6f, 0x75, 0x73, 0x65,
	0x22, 0x40, 0x0a, 0x23, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x65,
	0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x4f, 0x66, 0x48, 0x6f, 0x75, 0x73, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x68, 0x6f, 0x75, 0x73, 0x65,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x68, 0x6f, 0x75, 0x73, 0x65,
	0x49, 0x64, 0x22, 0x55, 0x0a, 0x24, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63,
	0x74, 0x65, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x4f, 0x66, 0x48, 0x6f, 0x75,
	0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2d, 0x0a, 0x12, 0x63, 0x6f,
	0x6e, 0x6e, 0x65, 0x63, 0x74, 0x65, 0x64, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x11, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x65,
	0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x32, 0xc2, 0x02, 0x0a, 0x0c, 0x48, 0x6f,
	0x75, 0x73, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x35, 0x0a, 0x06, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x12, 0x14, 0x2e, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x2e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x68, 0x6f, 0x75,
	0x73, 0x65, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x31, 0x0a, 0x04, 0x46, 0x69, 0x6e, 0x64, 0x12, 0x13, 0x2e, 0x68, 0x6f, 0x75, 0x73,
	0x65, 0x2e, 0x48, 0x6f, 0x75, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14,
	0x2e, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x2e, 0x48, 0x6f, 0x75, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4f, 0x0a, 0x0f, 0x4c, 0x69, 0x73, 0x74, 0x48, 0x6f, 0x75, 0x73,
	0x65, 0x73, 0x42, 0x79, 0x49, 0x64, 0x73, 0x12, 0x1d, 0x2e, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x2e,
	0x4c, 0x69, 0x73, 0x74, 0x48, 0x6f, 0x75, 0x73, 0x65, 0x73, 0x42, 0x79, 0x49, 0x64, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x2e, 0x4c,
	0x69, 0x73, 0x74, 0x48, 0x6f, 0x75, 0x73, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x28, 0x01, 0x30, 0x01, 0x12, 0x77, 0x0a, 0x1c, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6f, 0x6e,
	0x6e, 0x65, 0x63, 0x74, 0x65, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x4f, 0x66,
	0x48, 0x6f, 0x75, 0x73, 0x65, 0x12, 0x2a, 0x2e, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x2e, 0x4c, 0x69,
	0x73, 0x74, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x65, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x73, 0x4f, 0x66, 0x48, 0x6f, 0x75, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x2b, 0x2e, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6f,
	0x6e, 0x6e, 0x65, 0x63, 0x74, 0x65, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x4f,
	0x66, 0x48, 0x6f, 0x75, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x33,
	0x5a, 0x31, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x65, 0x68,
	0x72, 0x65, 0x6c, 0x74, 0x2f, 0x6d, 0x6f, 0x69, 0x2d, 0x75, 0x73, 0x6c, 0x75, 0x67, 0x69, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x3b, 0x68, 0x6f, 0x75, 0x73,
	0x65, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_proto_house_proto_rawDescOnce sync.Once
	file_proto_house_proto_rawDescData []byte
)

func file_proto_house_proto_rawDescGZIP() []byte {
	file_proto_house_proto_rawDescOnce.Do(func() {
		file_proto_house_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_house_proto_rawDesc), len(file_proto_house_proto_rawDesc)))
	})
	return file_proto_house_proto_rawDescData
}

var file_proto_house_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_house_proto_goTypes = []any{
	(*House)(nil),                                // 0: house.House
	(*CreateRequest)(nil),                        // 1: house.CreateRequest
	(*CreateResponse)(nil),                       // 2: house.CreateResponse
	(*HouseRequest)(nil),                         // 3: house.HouseRequest
	(*HouseResponse)(nil),                        // 4: house.HouseResponse
	(*ListHousesByIdsRequest)(nil),               // 5: house.ListHousesByIdsRequest
	(*ListHousesResponse)(nil),                   // 6: house.ListHousesResponse
	(*ListConnectedServicesOfHouseRequest)(nil),  // 7: house.ListConnectedServicesOfHouseRequest
	(*ListConnectedServicesOfHouseResponse)(nil), // 8: house.ListConnectedServicesOfHouseResponse
}
var file_proto_house_proto_depIdxs = []int32{
	0, // 0: house.HouseResponse.house:type_name -> house.House
	0, // 1: house.ListHousesResponse.house:type_name -> house.House
	1, // 2: house.HouseService.Create:input_type -> house.CreateRequest
	3, // 3: house.HouseService.Find:input_type -> house.HouseRequest
	5, // 4: house.HouseService.ListHousesByIds:input_type -> house.ListHousesByIdsRequest
	7, // 5: house.HouseService.ListConnectedServicesOfHouse:input_type -> house.ListConnectedServicesOfHouseRequest
	2, // 6: house.HouseService.Create:output_type -> house.CreateResponse
	4, // 7: house.HouseService.Find:output_type -> house.HouseResponse
	6, // 8: house.HouseService.ListHousesByIds:output_type -> house.ListHousesResponse
	8, // 9: house.HouseService.ListConnectedServicesOfHouse:output_type -> house.ListConnectedServicesOfHouseResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_house_proto_init() }
func file_proto_house_proto_init() {
	if File_proto_house_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_house_proto_rawDesc), len(file_proto_house_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_house_proto_goTypes,
		DependencyIndexes: file_proto_house_proto_depIdxs,
		MessageInfos:      file_proto_house_proto_msgTypes,
	}.Build()
	File_proto_house_proto = out.File
	file_proto_house_proto_goTypes = nil
	file_proto_house_proto_depIdxs = nil
}
