include:
  - user.yaml
  - auth.yaml
  - rmq.yaml
  - rate-service.yaml
  - housing-service.yaml
  - billing-service.yaml
  - register-service.yaml
  - account-service.yaml
  - ticket-service.yaml
  - consumption-service.yaml
  - notification-service.yaml
  - telegram-bot.yaml
  - mailer.yaml
  - gateway.yaml

services:
  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    ports:
      - "81:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=root@mu.ru
      - PGADMIN_DEFAULT_PASSWORD=rootroot
      - PGADMIN_LISTEN_PORT=80

  jaeger:
    image: jaegertracing/all-in-one
    restart: unless-stopped
    container_name: mu-jaeger
    ports:
      - "14268:14268"
      - "14269:14269"
      - "16686:16686"
      - "4317:4317"

  nginx:
    image: nginx:1-alpine
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    extra_hosts:
      - "host.docker.internal:host-gateway"
