services:
  rmq:
    container_name: mzhn-rabbitmq
    restart: unless-stopped
    image: rabbitmq:3-management
    volumes:
      - rmq-data:/data
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  rmq-data:
