// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.4
// source: proto/notification.proto

package notificationpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NotificationService_TelegramOtp_FullMethodName    = "/notification.NotificationService/TelegramOtp"
	NotificationService_LinkTelegram_FullMethodName   = "/notification.NotificationService/LinkTelegram"
	NotificationService_UnlinkTelegram_FullMethodName = "/notification.NotificationService/UnlinkTelegram"
)

// NotificationServiceClient is the client API for NotificationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NotificationServiceClient interface {
	TelegramOtp(ctx context.Context, in *TelegramOtpRequest, opts ...grpc.CallOption) (*TelegramOtpResponse, error)
	LinkTelegram(ctx context.Context, in *LinkTelegramRequest, opts ...grpc.CallOption) (*LinkTelegramResponse, error)
	UnlinkTelegram(ctx context.Context, in *UnlinkTelegramRequest, opts ...grpc.CallOption) (*UnlinkTelegramResponse, error)
}

type notificationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNotificationServiceClient(cc grpc.ClientConnInterface) NotificationServiceClient {
	return &notificationServiceClient{cc}
}

func (c *notificationServiceClient) TelegramOtp(ctx context.Context, in *TelegramOtpRequest, opts ...grpc.CallOption) (*TelegramOtpResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TelegramOtpResponse)
	err := c.cc.Invoke(ctx, NotificationService_TelegramOtp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) LinkTelegram(ctx context.Context, in *LinkTelegramRequest, opts ...grpc.CallOption) (*LinkTelegramResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LinkTelegramResponse)
	err := c.cc.Invoke(ctx, NotificationService_LinkTelegram_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) UnlinkTelegram(ctx context.Context, in *UnlinkTelegramRequest, opts ...grpc.CallOption) (*UnlinkTelegramResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnlinkTelegramResponse)
	err := c.cc.Invoke(ctx, NotificationService_UnlinkTelegram_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NotificationServiceServer is the server API for NotificationService service.
// All implementations must embed UnimplementedNotificationServiceServer
// for forward compatibility.
type NotificationServiceServer interface {
	TelegramOtp(context.Context, *TelegramOtpRequest) (*TelegramOtpResponse, error)
	LinkTelegram(context.Context, *LinkTelegramRequest) (*LinkTelegramResponse, error)
	UnlinkTelegram(context.Context, *UnlinkTelegramRequest) (*UnlinkTelegramResponse, error)
	mustEmbedUnimplementedNotificationServiceServer()
}

// UnimplementedNotificationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNotificationServiceServer struct{}

func (UnimplementedNotificationServiceServer) TelegramOtp(context.Context, *TelegramOtpRequest) (*TelegramOtpResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TelegramOtp not implemented")
}
func (UnimplementedNotificationServiceServer) LinkTelegram(context.Context, *LinkTelegramRequest) (*LinkTelegramResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LinkTelegram not implemented")
}
func (UnimplementedNotificationServiceServer) UnlinkTelegram(context.Context, *UnlinkTelegramRequest) (*UnlinkTelegramResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnlinkTelegram not implemented")
}
func (UnimplementedNotificationServiceServer) mustEmbedUnimplementedNotificationServiceServer() {}
func (UnimplementedNotificationServiceServer) testEmbeddedByValue()                             {}

// UnsafeNotificationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NotificationServiceServer will
// result in compilation errors.
type UnsafeNotificationServiceServer interface {
	mustEmbedUnimplementedNotificationServiceServer()
}

func RegisterNotificationServiceServer(s grpc.ServiceRegistrar, srv NotificationServiceServer) {
	// If the following call pancis, it indicates UnimplementedNotificationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NotificationService_ServiceDesc, srv)
}

func _NotificationService_TelegramOtp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TelegramOtpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).TelegramOtp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_TelegramOtp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).TelegramOtp(ctx, req.(*TelegramOtpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_LinkTelegram_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LinkTelegramRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).LinkTelegram(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_LinkTelegram_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).LinkTelegram(ctx, req.(*LinkTelegramRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_UnlinkTelegram_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnlinkTelegramRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).UnlinkTelegram(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_UnlinkTelegram_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).UnlinkTelegram(ctx, req.(*UnlinkTelegramRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NotificationService_ServiceDesc is the grpc.ServiceDesc for NotificationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NotificationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "notification.NotificationService",
	HandlerType: (*NotificationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TelegramOtp",
			Handler:    _NotificationService_TelegramOtp_Handler,
		},
		{
			MethodName: "LinkTelegram",
			Handler:    _NotificationService_LinkTelegram_Handler,
		},
		{
			MethodName: "UnlinkTelegram",
			Handler:    _NotificationService_UnlinkTelegram_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/notification.proto",
}
